name: dhan_saarthi
description: A Flutter application built as an interview task that showcases user authentication using Supabase, mutual fund analysis, interactive chart visualization, and personalized user watchlists.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Utils
  device_info_plus: ^10.1.2
  intl: ^0.19.0
  flutter_screenutil: ^5.8.4
  flutter_easyloading: ^3.0.5
  logger: ^2.0.1
  path_provider: ^2.0.14
  crypto: ^3.0.3

  # Network
  connectivity_plus: ^6.1.0
  cached_network_image: ^3.2.3
  http: ^1.2.0
  dio: ^5.3.2

  # Navigation & Notification
  url_launcher: ^6.1.12
  webview_flutter: ^4.2.4

  # Media (Image, Permission, Video)
  permission_handler: ^11.0.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.2
  file_picker: ^8.0.0+1
  readmore: ^3.0.0
  flutter_cache_manager: ^3.3.1


  # Firebase
  country_code_picker: ^3.0.0

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.4

  # Additional UI Elements (Toast, Popup, Addition Display)
  fluttertoast: ^8.2.12
  date_field: ^6.0.0
  fl_chart: ^1.0.0
  custom_sliding_segmented_control: ^1.8.5


  # Location
  geolocator: ^13.0.2

  # Other UI Elements
  flutter_animate: ^4.2.0+1
  timeago: ^3.6.0
  pin_input_text_field: ^4.5.2
  supabase_flutter: ^2.9.0


  package_info_plus: ^8.1.1
  uuid: ^4.5.1
  collection: any
  jwt_decoder: ^2.0.1
  flutter_dotenv: ^5.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700

